# Collaborative Filtering

<h3><i>1.Read about the movielens datasetand write down a summary of metadata.</i></h3>

This dataset (ml-latest-small) describes 5-star rating and free-text tagging activity from [MovieLens](http://movielens.org), a movie recommendation service. It contains 100836 ratings and 3683 tag applications across 9742 movies. These data were created by 610 users between March 29, 1996 and September 24, 2018. This dataset was generated on September 26, 2018.

Users were selected at random for inclusion. All selected users had rated at least 20 movies. No demographic information is included. Each user is represented by an id, and no other information is provided.


<h3><i>2. Read the “ratings.csv”file and create a pivot table with index=‘userId’,columns=‘movieId’,values = “rating.</i></h3>

In [2]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
from sklearn.metrics import pairwise_distances
from scipy.spatial.distance import cosine, correlation

df = pd.read_csv("ratings.csv")
df.describe()

userId        movieId         rating     timestamp
count  100836.000000  100836.000000  100836.000000  1.008360e+05
mean      326.127564   19435.295718       3.501557  1.205946e+09
std       182.618491   35530.987199       1.042529  2.162610e+08
min         1.000000       1.000000       0.500000  8.281246e+08
25%       177.000000    1199.000000       3.000000  1.019124e+09
50%       325.000000    2991.000000       3.500000  1.186087e+09
75%       477.000000    8122.000000       4.000000  1.435994e+09
max       610.000000  193609.000000       5.000000  1.537799e+09

In [5]:
data = pd.pivot(df,index="userId",columns="movieId",values="rating")
data.replace(np.nan, 0, inplace=True)
data

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           4.0     0.0     4.0     0.0     0.0     4.0     0.0     0.0   
2           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
5           4.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...         ...     ...     ...     ...     ...     ...     ...     ...   
606         2.5     0.0     0.0     0.0     0.0     0.0     2.5     0.0   
607         4.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
608         2.5     2.0     2.0     0.0     0.0     0.0     0.0     0.0   
609         3.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
610         5.0     0.0     0.0     0.0     0.0     5.0     0.0     0.0   

movieId  9       10      ...  193565  193567  193571  193573  193579  193581  \
userId                   ...                                                   
1           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
2           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
4           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
5           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
...         ...     ...  ...     ...     ...     ...     ...     ...     ...   
606         0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
607         0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
608         0.0     4.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
609         0.0     4.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
610         0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   

movieId  193583  193585  193587  193609  
userId                                   
1           0.0     0.0     0.0     0.0  
2           0.0     0.0     0.0     0.0  
3           0.0     0.0     0.0     0.0  
4           0.0     0.0     0.0     0.0  
5           0.0     0.0     0.0     0.0  
...         ...     ...     ...     ...  
606         0.0     0.0     0.0     0.0  
607         0.0     0.0     0.0     0.0  
608         0.0     0.0     0.0     0.0  
609         0.0     0.0     0.0     0.0  
610         0.0     0.0     0.0     0.0  

[610 rows x 9724 columns]

<h3><i>3. sklearn.metrics.pairwise_distances  can  be  used  to  compute  distance between  all  pairs  of users. pairwise_distances() takes a metric parameter for what distance measuretouse. Use cosine similarity for finding similarity among users. Usethe following packages.</i></h3>
    <ol>
        <li>from sklearn.metrics import pairwise_distances.</li>
        <li>from scipy.spatial.distance import cosine, correlation</li>
    </ol>
    

In [7]:
distances = pairwise_distances(data,metric="euclidean")

In [8]:
distances

array([[  0.        ,  70.43614129,  69.33613776, ...,  99.69829487,
         68.70225615, 143.37625326],
       [ 70.43614129,   0.        ,  29.45759664, ...,  96.99742265,
         29.14189424, 136.1396342 ],
       [ 69.33613776,  29.45759664,   0.        , ...,  97.19439284,
         28.2931087 , 137.45271914],
       ...,
       [ 99.69829487,  96.99742265,  97.19439284, ...,   0.        ,
         95.20898067, 139.25157091],
       [ 68.70225615,  29.14189424,  28.2931087 , ...,  95.20898067,
          0.        , 137.04652495],
       [143.37625326, 136.1396342 , 137.45271914, ..., 139.25157091,
        137.04652495,   0.        ]])

In [9]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(distances)
similarity

array([[1.        , 0.95437257, 0.95198987, ..., 0.99244875, 0.94588874,
        0.98661704],
       [0.95437257, 1.        , 0.99913437, ..., 0.92063287, 0.99790144,
        0.90612073],
       [0.95198987, 0.99913437, 1.        , ..., 0.91717531, 0.99846022,
        0.90209923],
       ...,
       [0.99244875, 0.92063287, 0.91717531, ..., 1.        , 0.90939531,
        0.9963107 ],
       [0.94588874, 0.99790144, 0.99846022, ..., 0.90939531, 1.        ,
        0.89325962],
       [0.98661704, 0.90612073, 0.90209923, ..., 0.9963107 , 0.89325962,
        1.        ]])

In [10]:
#sim = []
#for i in range(distances.shape[0]):
  #sim.

<h3><i>6. Find the 5 most similar user for user with user Id 10.</i></h3>

In [11]:
arr = [np.argsort(similarity[9])[-6:-1]]
usertop = np.asarray(arr)+1 
usertop

array([[ 83, 543, 460,  98, 523]], dtype=int32)

<h3><i>7. Use the “movies” dataset to find out the names of movies, user 2 and user 338 have watched in common and how they have rated each one of them.</i></h3>

In [12]:
movies = pd.read_csv("movies.csv")
movies

movieId                                      title  \
0           1                           Toy Story (1995)   
1           2                             Jumanji (1995)   
2           3                    Grumpier Old Men (1995)   
3           4                   Waiting to Exhale (1995)   
4           5         Father of the Bride Part II (1995)   
...       ...                                        ...   
9737   193581  Black Butler: Book of the Atlantic (2017)   
9738   193583               No Game No Life: Zero (2017)   
9739   193585                               Flint (2017)   
9740   193587        Bungo Stray Dogs: Dead Apple (2018)   
9741   193609        Andrew Dice Clay: Dice Rules (1991)   

                                           genres  
0     Adventure|Animation|Children|Comedy|Fantasy  
1                      Adventure|Children|Fantasy  
2                                  Comedy|Romance  
3                            Comedy|Drama|Romance  
4                                          Comedy  
...                                           ...  
9737              Action|Animation|Comedy|Fantasy  
9738                     Animation|Comedy|Fantasy  
9739                                        Drama  
9740                             Action|Animation  
9741                                       Comedy  

[9742 rows x 3 columns]

In [13]:
for i,id in enumerate(data.columns):
  user_2 = float(data[data.index==2][id])
  user_338 = float(data[data.index==338][id])
  if((user_2!=0.0) and (user_338!=0.0)):
    print(movies[movies["movieId"]==id]["title"])

277    Shawshank Redemption, The (1994)
Name: title, dtype: object
4615    Kill Bill: Vol. 1 (2003)
Name: title, dtype: object


<h3><i>8. Use the movies dataset to find out the common movie names between user 2 and user 338 with least rating of 4.0</i></h3>

In [14]:
for i,id in enumerate(data.columns):
  user_2 = float(data[data.index==2][id])
  user_338 = float(data[data.index==338][id])
  if((user_2>=4.0) and (user_338>=4.0)):
    print(movies[movies["movieId"]==id]["title"])

4615    Kill Bill: Vol. 1 (2003)
Name: title, dtype: object


<h3><i>9. Create a pivot table for representing the similarity among movies using correlation.</i></h3>

In [36]:
genre_set = ["Action","Adventure","Animation","Children","Comedy","Crime","Documentary","Drama","Fantasy",
             "Film-Noir","Horror","Musical","Mystery","Romance","Sci-Fi","Thriller","War","Western"]
genre_dict = {genre_set[i]:i+1 for i in range(0,len(genre_set))}
genre_dict

{'Action': 1,
 'Adventure': 2,
 'Animation': 3,
 'Children': 4,
 'Comedy': 5,
 'Crime': 6,
 'Documentary': 7,
 'Drama': 8,
 'Fantasy': 9,
 'Film-Noir': 10,
 'Horror': 11,
 'Musical': 12,
 'Mystery': 13,
 'Romance': 14,
 'Sci-Fi': 15,
 'Thriller': 16,
 'War': 17,
 'Western': 18}

In [37]:
genre = []
for i in movies.genres:
    sum=0;
    for j in i.split('|'):
        if j in genre_dict.keys():
            sum = sum + genre_dict[j]
    genre.append(sum)

In [39]:
movies["genre_sum"]=genre

In [102]:
movies

movieId                                      title  \
0           1                           Toy Story (1995)   
1           2                             Jumanji (1995)   
2           3                    Grumpier Old Men (1995)   
3           4                   Waiting to Exhale (1995)   
4           5         Father of the Bride Part II (1995)   
...       ...                                        ...   
9737   193581  Black Butler: Book of the Atlantic (2017)   
9738   193583               No Game No Life: Zero (2017)   
9739   193585                               Flint (2017)   
9740   193587        Bungo Stray Dogs: Dead Apple (2018)   
9741   193609        Andrew Dice Clay: Dice Rules (1991)   

                                           genres  genre_sum  
0     Adventure|Animation|Children|Comedy|Fantasy         23  
1                      Adventure|Children|Fantasy         15  
2                                  Comedy|Romance         19  
3                            Comedy|Drama|Romance         27  
4                                          Comedy          5  
...                                           ...        ...  
9737              Action|Animation|Comedy|Fantasy         18  
9738                     Animation|Comedy|Fantasy         17  
9739                                        Drama          8  
9740                             Action|Animation          4  
9741                                       Comedy          5  

[9742 rows x 4 columns]

In [ ]:
genre_corr = []
for i,j in range(movies.shape[0]):
    genre_corr.append(correlation(movies["genre_sum"][i],movies["movieId"][i]))

<h3><i>10. Find the top 5  movies which are similar tothe movie “Godfather”.</i></h3>

In [55]:
genre_corr = movies[["genre_sum","movieId"]].corr()

In [101]:
def corr(s1,s2):
    s1_c = s1 - s1.mean()
    s2_c = s2 - s2.mean()
    return np.sum(s1_c * s2_c)/np.sqrt(np.sum(s1_c**2)*np.sum(s2_c**2))
sim = []

for i in data.columns:
    if i == 858: # Id of "Godfather, The (1972)"
        continue
    cor = corr(data[858], data[i])
    if np.isnan(cor):
        continue
    else:
        sim.append((i,cor))

sim.sort(key = lambda tup: tup[1], reverse = True)

In [99]:
sim[:10]


[(1221, 0.7693896277811015),
 (1213, 0.5602459435098547),
 (1193, 0.49604822079110716),
 (1089, 0.442128140889738),
 (608, 0.4180423678749511),
 (1208, 0.41401057862515367),
 (4262, 0.40760792957705083),
 (912, 0.3975004722442377),
 (1214, 0.3964193510715889),
 (111, 0.39572282135457726)]

In [53]:
# These are the id's of movies similar to "Godfather"